### ISSUE TITLE
Leading zero in input address causes error or low score

### ISSUE THREAD

**Issue by bstratto** [bcgov/ols-geocoder#107]
When providing an address with a leading zero, the geocoder handles the address as follows:
- if the leading zero appears in a number that is a unit number (in an apartment building) the geocoder API does not return an address. The Address List editor returns a server error:
![Capture](https://user-images.githubusercontent.com/32557795/86032037-949d2080-b9eb-11ea-97dc-a55108a55bff.JPG)
- if the leading zero appears in a number that is the site number, the geocoder does not find the site
![Capture3](https://user-images.githubusercontent.com/32557795/86032331-083f2d80-b9ec-11ea-9413-4ed31c109a3c.JPG)

This issue was discovered while processing the HLTH low scores address file. There were 4 occurrences of addresses with a leading zero.

**Comment by cmhodgson** [comment]
In the first case, there is an error in the JSON output code which interprets the number with a leading zero as a valid number, and so outputs it without quotes around it, but it is not a valid number in JSON, so it produces a parsing error when the ALE tries to interpret the javascript. I've fixed this issue in my local code. Units names/numbers are allowed to be arbitrary strings so we don't force the removal of the leading zero to coerce it into a valid number.

In the second case, a leading zero is interpreted as a negative address number. This may have been added when we were trying to support Portland/Tri-city area... I don't think this is an actual thing in BC, although I think we found it was done in multiple US cities, where numbering in one direction of a "main" street was using the same numbers as the opposite direction but with leading zeros to indicate negative addresses. Perhaps we should remove this function, or we should have a fallback to the positive value of the address with a fault with a small penalty.

**Comment by cmhodgson** [comment]
fallback to positive with penalty is an acceptable solution.

**Comment by alixcote** [comment]
This is now resolved. Closing.
![image](https://user-images.githubusercontent.com/89096395/228927884-85a02929-5c8c-4d13-9fef-fd3bde08f697.png)

**Comment by gleeming** [comment]
Note that the second case where the civic number has a leading zero still fails as the code treats this as a negative number as per Chris' comment.  The fallback to positive with minor penalty was never implemented

**Comment by alixcote** [comment]
Will leave open to consider the second issue, although it was noted only 4 addresses in the health file had this issue.
